let categorys = [
    {
        'category' : ['Vorspeisen','Salate', 'Pizza'],
        'categoryImg' : ['./img/starters.jpeg', './img/salad.jpg', './img/pizza.jpg'],
    },
]



let food = [

    {
        'amount': 0,
        'item': 'Bruschetta',
        'itemdescription': 'Belag aus gehackten Tomaten, frischem Basilikum, Knoblauch und Zwiebeln',
        'pick': "false",
        'price': "8,50",
        'category': 'Vorspeise',
    },
    {
        'amount': 0,
        'item': 'Scampispieß',
        'itemdescription': 'mit Weißweinsauce und Knoblauch',
        'pick': "false",
        'price': "13,00",
        'category': 'Vorspeise',
    },
    {
        'amount': 0,
        'item': 'Funghi al Forno',
        'itemdescription': 'überbackene Champignons',
        'pick': "false",
        'price': "10,50",
        'category': 'Vorspeise',
    },
    {
        'amount': 0,
        'item': 'Caprese',
        'itemdescription': 'Mozzarella mit Scheibentomaten und Pizzabrot',
        'pick': "false",
        'price': "12,00",
        'category': 'Vorspeise',
    },
    {
        'amount': 0,
        'item': 'Gemischter Salat',
        'itemdescription': 'Salat mit Gurken, Tomaten und Zwiebeln',
        'pick': "false",
        'price': "7,50",
        'category': 'Salate',
    },
    {
        'amount': 0,
        'item': 'Italienischer Salat',
        'itemdescription': 'Salat mit Gurken, Tomaten, Käse, Ei, Schinken und Thunfisch',
        'pick': "false",
        'price': "9,00",
        'category': 'Salate',
    },
    {
        'amount': 0,
        'item': 'Beilagensalat',
        'itemdescription': 'mit Gurken und Tomaten',
        'pick': "false",
        'price': "5,00",
        'category': 'Salate',
    },
    {
        'amount': 0,
        'item': 'Salat Milano',
        'itemdescription': 'gemischter Salat mit Tomaten, Gurken, Artischocken, milder Peperoni, Mais, Paprika, Schinken, Käse, Thunfisch, Parmesan und Oliven, dazu Pizzabrot',
        'pick': "false",
        'price': "15,50",
        'category': 'Salate',
    },
    {
        'amount': 0,
        'item': 'Pizza Margherita',
        'itemdescription': 'Mozzarella und Tomatensoße',
        'pick': "false",
        'price': "7,50",
        'category': 'Pizza',
    },
    {
        'amount': 0,
        'item': 'Pizza Milano',
        'itemdescription': 'mit frischen Champignons, Salami und Schinken',
        'pick': "false",
        'price': "10,00",
        'category': 'Pizza',
    },
    {
        'amount': 0,
        'item': 'Pizza Toscana',
        'itemdescription': 'mit frischen Champignons, Salami, Schinken, Zwiebeln, Paprika und Peperoniwurst',
        'pick': "false",
        'price': "12,00",
        'category': 'Pizza',
    },
    {
        'amount': 0,
        'item': 'Pizza Spinaci',
        'itemdescription': 'mit Spinat und Knoblauch',
        'pick': "false",
        'price': "10,50",
        'category': 'Pizza',
    },
    {
        'amount': 0,
        'item': 'Pizza Vegetaria',
        'itemdescription': 'mit frischen Champignons, Zwiebeln, Paprika, Artischocken, Broccoli und Knoblauch',
        'pick': "false",
        'price': "12,00",
        'category': 'Pizza',
    },
    {
        'amount': 0,
        'item': 'Pizza Parma',
        'itemdescription': 'mit Mozzarella, Parmaschinken und Rucola',
        'pick': "false",
        'price': "13,00",
        'category': 'Pizza',
    },
]
